### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by larsbutler** [SamyPesse/tv.js#17]
This project is really neat and it seems to have gained a lot of interest. However, it is lacking a license which would allow people to use it flexibly in an open source context.

Without a explicit license, code is "is protected by copyright and is by default All Rights Reserved" (see http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github).

Would you like to release this software under an open source license? If so, please include a LICENSE file.

It's your code, of course, and you can do with it as you wish. Just a friendly suggestion/request. =)

Cheers!

**Comment by SamyPesse** [comment]
Thanks, I just added the Apache Licence 2a7ef9208408b4e562f143caa2508c78ce32b469
