### ISSUE TITLE
Connect to 0.0.0.0/remote/

### ISSUE THREAD

**Issue by localjo** [SamyPesse/tv.js#18]
The initial page loads and says "Connect a remote control by visiting 0.0.0.0/remote/ on your smartphone". I tried loading 192.168.0.107 (my Pi's local IP) and 0.0.0.0 which I'm assuming is an error, and neither could be reached.

Any ideas about what's going on here?

**Comment by localjo** [comment]
If I go to 192.168.0.107:8123/remote/ (I changed the port to avoid conflicts with Btsync), I can access the remote. When I type in a search term, the URL in the location bar on my Pi changes to /#/search/term, but the page displayed in the viewport never changes from the initial screen.

**Comment by localjo** [comment]
If I access "192.168.0.107:8123/#/search/star trek" on my laptop, it seems to be working (slowly), but still nothing on my Pi.

**Comment by ssilverm** [comment]
I'm having the same issue on the Pi.

I get 0.0.0.0/remote, but i can't access the remote either through localhost, 0.0.0.0, 127.0.0.1, or Raspberry Pi's actual LAN ip.

I can reach the page on my laptop via the Pi web server, but it never works on the Pi itself.

**Comment by ggaspari** [comment]
How did you change the port for the remote server?

**Comment by localjo** [comment]
Did a search and replace and replaced :8888 with :8123

https://github.com/SamyPesse/tv.js/search?q=%3A8888&source=cc

Found one more in package.json

**Comment by SamyPesse** [comment]
Define **port** in config.js or set the environment variable PORT

**Comment by localjo** [comment]
Where is config.js?

**Comment by SamyPesse** [comment]
https://github.com/SamyPesse/tv.js/blob/master/config.js
(pull the repository)
