### ISSUE TITLE
Failed to load NSS libraries

### ISSUE THREAD

**Issue by aranw** [SamyPesse/tv.js#19]
As the title says...

```
pi@raspberrypi ~/tv.js $ chromium --kiosk http://localhost:8888
[1:1:291244497:ERROR:nss_util.cc(692)] Failed to load NSS libraries.

(chromium:2203): Gtk-WARNING **: cannot open display: 

```

**Comment by aranw** [comment]
Fixed the NSS Libraries by symlinking /usr/lib/arm-linux-gnueabihf/nss/ too /usr/lib/nss

**Comment by rafkid** [comment]
And for the noobs among us the command to do this is:

sudo ln -s /usr/lib/arm-linux-gnueabihf/nss/ /usr/lib/nss

which works - or it did for my rpi anyway :)

Found at: http://raspberrypi.stackexchange.com/questions/11956/launching-chromium-browser-via-terminal-throws-errors

**Comment by billca42** [comment]
Worked for me, too. Thanks!
