### ISSUE TITLE
Error when try to install yapp

### ISSUE THREAD

**Issue by carlosvillu** [SamyPesse/tv.js#2]
There is other way to have Yapp in the system cos is imposible to me install it ... always have the same public key error

npm ERR! git clone git@github.com:FriendCode/yapp.js.git Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-FriendCode-yapp-js-git-f3169622'...
npm ERR! git clone git@github.com:FriendCode/yapp.js.git 
npm ERR! git clone git@github.com:FriendCode/yapp.js.git Permission denied (publickey).
npm ERR! git clone git@github.com:FriendCode/yapp.js.git fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:FriendCode/yapp.js.git 
npm ERR! git clone git@github.com:FriendCode/yapp.js.git Please make sure you have the correct access rights
npm ERR! git clone git@github.com:FriendCode/yapp.js.git and the repository exists.
npm ERR! Error: Command failed: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:735:16)
npm ERR!     at Socket.<anonymous> (child_process.js:948:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:451:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "git+ssh://git@github.com:FriendCode/yapp.js.git#master"
npm ERR! cwd /home/ubuntu/tv.js
npm ERR! node -v v0.10.10
npm ERR! npm -v 1.2.25
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/tv.js/npm-debug.log
npm ERR! not ok code 0

**Comment by SamyPesse** [comment]
A pushed a fix : 

```
npm install -g git://github.com/FriendCode/yapp.js.git#master
```

instead of

```
npm install -g git+ssh://git@github.com:FriendCode/yapp.js.git#master
```
