### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by aranw** [SamyPesse/tv.js#21]
Unable to get the browser to load

```
pi@raspberrypi ~/tv.js $ chromium --kiosk http://localhost:8888

(chromium:2241): Gtk-WARNING **: cannot open display: 
```

**Comment by ssilverm** [comment]
are you in the window environment?  not just ont he command line.  type startx after logging in.

**Comment by aranw** [comment]
Oh so can't do this straight from command line? I was hoping to have this load up on start up :/

**Comment by ssilverm** [comment]
You can use raspi-config to start x at boot, and then you can place a startup command like this: http://wiki.lxde.org/en/Autostart

**Comment by aranw** [comment]
I've found a tutorial that'll allow me (I think) set chromium to start as the XSession. I'll report back to this issue with my results of the tutorial and whether it does what I want.

**Comment by AaronO** [comment]
@SamyPesse commited a README of his installation process on Raspberry Pi (I'm recieving mine tomorrow hopefully :) ).

Check it out here: https://github.com/SamyPesse/tv.js/blob/master/raspberrypi/.

All the steps work well, besides 9 and 10, which i'll look into (the init script needs fixed).

**Comment by aranw** [comment]
Using this tutorial as a rough guide I was able to get Chromium to be full screen without having to start the full X server. 

http://nexxylove.tumblr.com/post/22690398464/ubuntu-web-kiosk-in-10-easy-steps
