### ISSUE TITLE
Portable APP

### ISSUE THREAD

**Issue by Lowmach1ne** [SamyPesse/tv.js#35]
Hello,

Can you upload a portable version like 1 exe with node-webkit ?

Thx and Good Job

**Comment by SamyPesse** [comment]
The problem is that we are using an external executable (ffmpeg) so it's not possible to upload a portable version with tv.js and ffmpeg.
The user have to install by himself ffmpeg.

**Comment by nickdima** [comment]
Why do you use ffmpeg? You do remuxing of the stream to make sure it's playable in the browser?
I did a test playing the stream directly as it comes from peerflix in the browser with video.js and it worked. But it was just a quick test with one torrent...
