### ISSUE TITLE
Slow On RapsberryPi

### ISSUE THREAD

**Issue by poxrud** [SamyPesse/tv.js#36]
Is the yutube demo showcasing tv.js showing a raspberrypi?

I've got tv.js successfully installed on my raspberrypi but it is running unbearably slow. 
When trying to search I am getting 1 minute delays between autocomplete refreshes for each letter typed. 

My pi is overclocked to 900Mhz

I'm trying to figure our if there is something wrong with my configuration or is this a limitation of the pi's hardware? If it is the latter then I don't think the pi is the right platform for this project.

**Comment by robertfsegal** [comment]
I'm running into this issue as well.  When connecting externally through another machine on the network it's pretty snappy except for the fact I haven't been able to stream any videos yet but I believe this is a separate issue.  The actual UI is extremely quick when connecting from my Macbook Pro in Google Chrome.

**Comment by SamyPesse** [comment]
Yes tv.js is slow on a rapsberry Pi, we need to improve UI rendering and use less animations.
On the backend, we need to prioritize MP4 movies using x264 to avoid transcoding (#9).
