### ISSUE TITLE
Potentially wrong path to yapp in the Makefile

### ISSUE THREAD

**Issue by ernadh** [SamyPesse/tv.js#38]
I've just tried building the app. 

Make install works just fine but make takes a wrong route to yapp.

``` unix
YAPP = node_modules/yapp/bin/yapp.js
```

However, yapp is actually installed in

``` unix
node_modules/yapp.js/bin/yapp.js
```

I'm running the latest node. I didn't want to issue a pull request because this might be specific to this particular node.

**Comment by SamyPesse** [comment]
You're right. Sorry for the error, we change the package name for yapp to "yapp.js" few days ago.
It's fixed now : 09db1a991fd5cfa69b95988c4aedbad15da5e296
