### ISSUE TITLE
API Suggestion

### ISSUE THREAD

**Issue by craigcoles** [SamyPesse/tv.js#8]
In your 'To Do' section, you mentioned:

> Use IMBD or another API with a bigger movie collection that Itunes'

IMDB does not have an API, but I would highly recommend The Movie DB (http://www.themoviedb.org/).

The Movie DB API Docs - http://docs.themoviedb.apiary.io/

**Comment by AaronO** [comment]
You're correct :+1:  I just wrote that off the top of my head (everything in this repo was done in the last 24 hours).

Itunes' movie catalog isn't fully complete indeed. Do you know how The Movie DB's database compares to iTunes'.

If it's considerably better, we'll probably switch.

**Comment by carlbarrdahl** [comment]
This one seems to be pretty good:
http://www.omdbapi.com/

Or: http://www.imdb.com/xml/find?json=1&nr=1&tt=on&q=fight%20club

I few years ago I did an improved search engine for imdb, maybe you could do something similar? I took the lazy approach of scraping their top votes movies and push into my own database to prioritize quick search before updated data.
http://movies.carlbarrdahl.se

**Comment by AaronO** [comment]
Something interesting might be to add trailers. (Lets be careful about feature creep) 

I'll talk over the different API possibilities with Samy as soon as he's back online

**Comment by qq99** [comment]
Trailers would be neat, but personally I find they weaken the movie watching experience
